FROM mcr.microsoft.com/dotnet/sdk:7.0 AS testrunner
WORKDIR /app

# Копируем все файлы проекта
COPY . ./

# Восстанавливаем зависимости
RUN dotnet restore

# Собираем тестовые проекты
RUN dotnet build -c Release --no-restore

# Создаем директорию для результатов тестов
RUN mkdir -p TestResults

WORKDIR /app/FlowerShop